language: go
sudo: false
go:
  - 1.8.x
  - 1.9.x
  - tip
os:
  - linux
  - osx
env:
  matrix:
    - GOARCH=amd64 DOCKER_PKG_VERSION=17.06.0~ce-0~ubuntu
    - GOARCH=386   DOCKER_PKG_VERSION=17.06.0~ce-0~ubuntu
    - GOARCH=amd64 DOCKER_PKG_VERSION=17.05.0~ce-0~ubuntu-trusty
    - GOARCH=386   DOCKER_PKG_VERSION=17.05.0~ce-0~ubuntu-trusty
script:
  - make test
matrix:
  fast_finish: true
  exclude:
    - os: osx
      env: GOARCH=amd64 DOCKER_PKG_VERSION=17.05.0~ce-0~ubuntu-trusty
    - os: osx
      env: GOARCH=386   DOCKER_PKG_VERSION=17.05.0~ce-0~ubuntu-trusty
