version: "{build}"

clone_depth: 1
clone_folder: c:\gopath\src\github.com\mavogel\go-ssh-forward

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - set PATH=%PATH%;%GOPATH%\bin

test_script:
  - for /f "" %%G in ('go list github.com/mavogel/go-ssh-forward/...') do ( go test -v %%G & IF ERRORLEVEL == 1 EXIT 1)

build: off
deploy: off
